# This workflow will build and push a GAGA Docker image to Azure container registry
#
# This workflow assumes Azure container registry is already created 
#
# Secret are needed to be added in github repository. Service Principle will need to be created before hand.
# Adding new description line 



name: Build and Deploy Container App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'                                                  #Checkout Github Repository
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'                                                     #Login into Azure using service principal
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'                                                     #Build and push docker image to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}                             # set GAGA Container registry - crd0203use001.azurecr.io 
          username: ${{secrets.REGISTRY_UN}}                                             # Service principle details
          password: ${{secrets.RESGISTRY_PW}}                                            # Service principle details
      - run: |                                                                           # set GAGA Container registry - crd0203use001.azurecr.io
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/gaga:${{ github.sha }}    
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/gaga:${{ github.sha }}

      - name: 'Deploy to Azure Container Instances'                                      #Deploy ACR image to Web App
        uses: 'azure/aci-deploy@v1'
        with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/gaga:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_UN }}
            registry-password: ${{ secrets.RESGISTRY_PW }}
            name: test-webapp-gaga
            location: 'East US '


